# To Do: Split into seperate YAML
default_config:
# To Do: Split into seperate YAML
tts:
  - platform: google_translate

# Front End Configuration
frontend: !include configurations/frontend.conf.yaml
# Front End Configuration
lovelace: !include configurations/lovelace.conf.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
