# To Do: Split into seperate YAML
default_config:
# To Do: Split into seperate YAML
tts:
  - platform: google_translate

# Front-end Configuration
frontend: !include configurations/frontend.conf.yaml
# Lovelace Configuration
lovelace: !include configurations/lovelace.conf.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
