# To Do: Split into seperate YAML
default_config:
# To Do: Split into seperate YAML
tts:
  - platform: google_translate

# Prometheus Configuration
prometheus:
# Recorder Configuration
recorder: !include configurations/recorder.conf.yaml
# InfluxDB configuration
influxdb: !include configurations/influxdb.conf.yaml
# Front-end Configuration
frontend: !include configurations/frontend.conf.yaml
# Lovelace Configuration
lovelace: !include configurations/lovelace.conf.yaml
# Group Configuration
group: !include_dir_named configurations/groups/
# Sensor configurations
sensor: !include_dir_merge_list configurations/sensor
# Switch Configurations
switch: 
- platform: circadian_lighting
  name: circadian_lighting_office
  lights_ct:
    - light.office_desk
    - light.office_desk_lamp
    - light.office_door
    - light.office_netcab

- platform: circadian_lighting
  name: circadian_lighting_bathroom
  lights_ct:
    - light.bathroom_sink_r
    - light.bathroom_sink_f
    - light.bathroom_shower_r
    - light.bathroom_shower_f
    - light.bathroom_bath_r
    - light.bathroom_bath_f

- platform: circadian_lighting
  name: circadian_lighting_bedroom
  lights_ct:
    - light.bathroom_bedroom_1
    - light.bathroom_bedroom_2

- platform: circadian_lighting
  name: circadian_lighting_kitchen
  lights_ct:
    - light.bathroom_kitchen_stovetop
    - light.bathroom_kitchen_sink
    - light.bathroom_kitchen_bench

- platform: circadian_lighting
  name: circadian_lighting_living
  lights_ct:
    - light.living_ceiling_1
    - light.living_ceiling_2
    - light.living_ceiling_3
    - light.living_ceiling_4
    - light.living_seating_lamp
    - light.living_dining_table

#Circadian Configuration
circadian_lighting: 

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
