# To Do: Split into seperate YAML
default_config:
# To Do: Split into seperate YAML
tts:
  - platform: google_translate


# Recorder Configuration
recorder: !include configurations/recorder.conf.yaml
# InfluxDB configuration
influxdb: !include configurations/influxdb.conf.yaml
# Front-end Configuration
frontend: !include configurations/frontend.conf.yaml
# Lovelace Configuration
lovelace: !include configurations/lovelace.conf.yaml
# Group Configuration
group: !include_dir_named configurations/groups/
# Sensor configurations
sensor: !include_dir_merge_list configurations/sensor
# Switch Configurations
switch: 
- platform: circadian_lighting
  name: circadian_lighting_office
  lights_ct:
    - light.office_desk
    - light.office_desk_lamp
    - light.office_door
    - light.office_netcab
#Circadian Configuration
circadian_lighting: 

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
