# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: Office
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  networkInterface: eth0
  autoDiscovery: false
  port: 6425
  weight: 90
  peerAddresses:
    - 192.168.128.10:6425
    - 192.168.128.11:6425
    - 192.168.128.12:6425
    - 192.168.128.13:6425
    - 192.168.128.14:6425
bluetoothLowEnergy:
  allowlist:
    - ecc179cda1194a09b4afd39955bdd424-100-1
    - e0eed4eec1a340e0a052b86e8bd6e4ef-100-1
    - 2a55ffffffffffffffffffffffffff01-65535-65535
    - 2a55ffffffffffffffffffffffffff02-65535-65535
    - 66758D66-0381-491B-9B25-F8E85FD4DAFE
  tagOverrides:
    ecc179cda1194a09b4afd39955bdd424-100-1:
      name: 'Marty Phone'
    2a55ffffffffffffffffffffffffff01-65535-65535:
      name: 'Marty BLE Tag'
    e0eed4eec1a340e0a052b86e8bd6e4ef-100-1:
      name: 'Lukasz Phone'
    2a55ffffffffffffffffffffffffff02-65535-65535:
      name: 'Lukasz BLE Tag'
    66758D66-0381-491B-9B25-F8E85FD4DAFE:
      name: 'Marty iPhone'
logger:
    elasticsearch:
        enabled: true
        node: http://10.32.32.247:9200
