# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: networkCabinet
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
cluster:
  networkInterface: eth0
  autoDiscovery: false
  port: 6425
  weight: 90
  peerAddresses:
    - 192.168.128.10:6425
bluetoothLowEnergy:
  allowlist:
    - ecc179cda1194a09b4afd39955bdd424-100-1
  tagOverrides:
    ecc179cda1194a09b4afd39955bdd424-100-1:
      name: 'phoneMarty'
