- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret sonarr_host
  port: 443
  days: 7
  ssl: true

- platform: plex_recently_added
  token: !secret plex_api_key
  host: !secret plex_host
  port: 32400

- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret radarr_host
  port: 443
  days: 31
  ssl: true